# Лабораторная работа №5
## Ансамбли моделей машинного обучения. Часть 1.
---

## Импорт библиотек и загрузка данных

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, f1_score, classification_report

from sklearn.ensemble import (
    BaggingClassifier,
    RandomForestClassifier,
    AdaBoostClassifier,
    GradientBoostingClassifier
)

sns.set_theme(style="whitegrid", palette="muted", font_scale=1.1)
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['figure.dpi'] = 100

import warnings
warnings.filterwarnings('ignore')

In [2]:
digits = load_digits()

df = pd.DataFrame(digits.data, columns=digits.feature_names)
df['target'] = digits.target
df['target_name'] = df['target'].map(dict(enumerate(digits.target_names)))

df.head(10)

   pixel_0_0  pixel_0_1  pixel_0_2  ...  pixel_7_7  target  target_name
0        0.0        0.0        5.0  ...        0.0       0            0
1        0.0        0.0        0.0  ...        0.0       1            1
2        0.0        0.0        0.0  ...        0.0       2            2
3        0.0        0.0        7.0  ...        0.0       3            3
4        0.0        0.0        0.0  ...        0.0       4            4
5        0.0        0.0       12.0  ...        0.0       5            5
6        0.0        0.0        0.0  ...        0.0       6            6
7        0.0        0.0        7.0  ...        0.0       7            7
8        0.0        0.0        9.0  ...        0.0       8            8
9        0.0        0.0       11.0  ...        0.0       9            9

[10 rows x 66 columns]

## Подготовка данных

In [3]:
X = df[digits.feature_names].values
y = df['target'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

In [4]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## Обучение моделей

#### Бэггинг

In [5]:
bag_model = BaggingClassifier(n_estimators=100, random_state=42)
bag_model.fit(X_train_scaled, y_train)

y_pred_bag = bag_model.predict(X_test_scaled)
acc_bag = accuracy_score(y_test, y_pred_bag)
f1_bag = f1_score(y_test, y_pred_bag, average='weighted')

print(f'Accuracy: {acc_bag:.4f}')
print(f'F1-score (weighted): {f1_bag:.4f}')
print(classification_report(y_test, y_pred_bag))

Accuracy: 0.9222
F1-score (weighted): 0.9224
              precision    recall  f1-score   support

           0       0.92      0.91      0.92        54
           1       0.88      0.95      0.91        55
           2       1.00      0.91      0.95        53
           3       0.95      0.95      0.95        55
           4       0.91      0.96      0.94        54
           5       0.96      0.93      0.94        55
           6       1.00      0.96      0.98        54
           7       0.93      1.00      0.96        54
           8       0.79      0.85      0.81        52
           9       0.90      0.81      0.85        54

    accuracy                           0.92       540
   macro avg       0.92      0.92      0.92       540
weighted avg       0.92      0.92      0.92       540

#### Случайный лес

In [6]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train_scaled, y_train)

y_pred_rf = rf_model.predict(X_test_scaled)
acc_rf = accuracy_score(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf, average='weighted')

print(f'Accuracy: {acc_rf:.4f}')
print(f'F1-score (weighted): {f1_rf:.4f}')
print(classification_report(y_test, y_pred_rf))

Accuracy: 0.9685
F1-score (weighted): 0.9684
              precision    recall  f1-score   support

           0       1.00      0.96      0.98        54
           1       0.93      1.00      0.96        55
           2       1.00      1.00      1.00        53
           3       0.96      0.98      0.97        55
           4       0.96      0.98      0.97        54
           5       1.00      0.98      0.99        55
           6       1.00      0.98      0.99        54
           7       0.92      1.00      0.96        54
           8       0.96      0.88      0.92        52
           9       0.96      0.91      0.93        54

    accuracy                           0.97       540
   macro avg       0.97      0.97      0.97       540
weighted avg       0.97      0.97      0.97       540

#### AdaBoost

In [7]:
ada_model = AdaBoostClassifier(n_estimators=100, random_state=42)
ada_model.fit(X_train_scaled, y_train)

y_pred_ada = ada_model.predict(X_test_scaled)
acc_ada = accuracy_score(y_test, y_pred_ada)
f1_ada = f1_score(y_test, y_pred_ada, average='weighted')

print(f'Accuracy: {acc_ada:.4f}')
print(f'F1-score (weighted): {f1_ada:.4f}')
print(classification_report(y_test, y_pred_ada))

Accuracy: 0.8167
F1-score (weighted): 0.8214
              precision    recall  f1-score   support

           0       0.94      0.93      0.93        54
           1       0.63      0.60      0.62        55
           2       0.93      0.79      0.86        53
           3       0.87      0.85      0.86        55
           4       0.89      0.74      0.81        54
           5       0.96      0.91      0.93        55
           6       0.98      0.89      0.93        54
           7       0.85      0.83      0.84        54
           8       0.55      0.83      0.66        52
           9       0.73      0.80      0.76        54

    accuracy                           0.82       540
   macro avg       0.83      0.82      0.82       540
weighted avg       0.83      0.82      0.82       540

#### Градиентный бустинг

In [8]:
gb_model = GradientBoostingClassifier(n_estimators=100, random_state=42)
gb_model.fit(X_train_scaled, y_train)

y_pred_gb = gb_model.predict(X_test_scaled)
acc_gb = accuracy_score(y_test, y_pred_gb)
f1_gb = f1_score(y_test, y_pred_gb, average='weighted')

print(f'Accuracy: {acc_gb:.4f}')
print(f'F1-score (weighted): {f1_gb:.4f}')
print(classification_report(y_test, y_pred_gb))

Accuracy: 0.9407
F1-score (weighted): 0.9404
              precision    recall  f1-score   support

           0       0.96      0.91      0.93        54
           1       0.92      0.87      0.90        55
           2       0.96      0.98      0.97        53
           3       0.95      0.98      0.96        55
           4       0.98      0.96      0.97        54
           5       0.95      0.96      0.95        55
           6       0.96      0.96      0.96        54
           7       0.90      1.00      0.95        54
           8       0.89      0.90      0.90        52
           9       0.94      0.87      0.90        54

    accuracy                           0.94       540
   macro avg       0.94      0.94      0.94       540
weighted avg       0.94      0.94      0.94       540

## Сравнение моделей

In [9]:
results = pd.DataFrame({
    'Модель': ['Бэггинг', 'Случайный лес', 'AdaBoost', 'Градиентный бустинг'],
    'Accuracy': [acc_bag, acc_rf, acc_ada, acc_gb],
    'F1-score (weighted)': [f1_bag, f1_rf, f1_ada, f1_gb]
})

results

                Модель  Accuracy  F1-score (weighted)
0              Бэггинг  0.922222             0.922421
1        Случайный лес  0.968519             0.968370
2             AdaBoost  0.816667             0.821368
3  Градиентный бустинг  0.940741             0.940411

In [19]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(1000,1000, 1000, 1000))
mlp.fit(X_train_scaled, y_train)

y_pred_mlp = mlp.predict(X_test_scaled)
acc_mlp = accuracy_score(y_test, y_pred_mlp)
f1_mlp = f1_score(y_test, y_pred_mlp, average='weighted')

print(f'Accuracy: {acc_mlp:.4f}')
print(f'F1-score (weighted): {f1_mlp:.4f}')
print(classification_report(y_test, y_pred_mlp))

Accuracy: 0.9796
F1-score (weighted): 0.9796
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        54
           1       0.95      0.98      0.96        55
           2       1.00      0.98      0.99        53
           3       0.98      1.00      0.99        55
           4       0.95      0.96      0.95        54
           5       1.00      0.98      0.99        55
           6       1.00      0.98      0.99        54
           7       1.00      1.00      1.00        54
           8       0.96      0.92      0.94        52
           9       0.96      1.00      0.98        54

    accuracy                           0.98       540
   macro avg       0.98      0.98      0.98       540
weighted avg       0.98      0.98      0.98       540